# =========================
# 1. Build React + Vite
# =========================
FROM node:24-alpine AS frontend

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


# =========================
# 2. Laravel + FrankenPHP
# =========================
FROM dunglas/frankenphp:php8.3-bookworm

WORKDIR /app

RUN install-php-extensions \
    pdo_mysql \
    mbstring \
    bcmath \
    exif \
    pcntl \
    opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

COPY . .

# Copy hasil build React/Vite
COPY --from=frontend /app/public/build ./public/build

RUN php artisan optimize:clear

RUN php artisan storage:link || true

RUN chown -R www-data:www-data \
    storage \
    bootstrap/cache

EXPOSE 80

CMD ["sh", "-c", "frankenphp php-server --listen 0.0.0.0:${PORT:-80} --root /app/public"]
